deploy:
  provider: s3
  access_key_id: AKIAIAVQAXMLLEPM4I5A
  secret_access_key:
    secure: jXsdvhUKP4aprPi6gWNUE0oVOWaLtA8jisCvBUgDE5QOWNCFDk/vCElQ3spxeDSMRw38WAsBtMbDgOboy6XynnWXNrJYaWJUR0EMdnrhsgy3Vuwr2LZst9O5OnWqX54HnCl4pD5ZpjD83Ez4/yOHLuMeZnfsFxmCn9SgMBrbnyt2jJnTEq344+8DUHaVAmUwKTvDpldpWF5k4hD0jPpsIPUadEMtO5a7fVsdd0qBSGUdepCd8JG+4GkW/y1SP4aBk1ZppD81PnMHGku44K4aA3F4OeXh685jKnuaqkBbbkOuBggFkXCOBRZOtk+eTZUi8KRWqu1qHVTGi6x4OrTAOgcdYkieiOgDecNND5zNi6208Xa4z1f8inysmnnoJzRNM9cVKwzvldvjqSzR74G/b0slkTVmSY2WV9JDDHbn48tIKRrsvid1sG5W6py1oVO1O1IDN0Ki/YY2OpRqr0LS4AeA8iW9Ab0BPHO//HwnA1lpOkkZgmTGDonXOmtezf75MPWVeJBIqEUZHLg/bxL2x61e7tKTe2zueeqXsEULgS862h8ILI3oh5uVuYNxRJRBiKXWK+ssnj33uaVbFTPfAw/y7OmoFS9+aOXHlbMGRS2NqkA6Z1xDvFM2IGfyeo7EY2TBjOCTGg0jZtjn2HT5/LMxgkdRkczivIkaQV6BjL4=
  bucket: stackage-travis
  acl: public_read
  skip_cleanup: true
  local_dir: to-travis
  upload-dir: all-cabal-metadata-tool
  on:
    repo: commercialhaskell/all-cabal-metadata-tool
    branch: master

# Use new container infrastructure to enable caching
sudo: false

# Choose a lightweight base image; we provide our own build tools.
language: c

# GHC depends on GMP. You can add other dependencies here as well.
addons:
  apt:
    packages:
    - libgmp-dev

# The different configurations we want to test. You could also do things like
# change flags or use --stack-yaml to point to a different file.
env:
- ARGS=""

before_install:
# Download and unpack the stack executable
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- travis_retry curl -L https://github.com/commercialhaskell/stack/releases/download/v0.1.4.0/stack-0.1.4.0-x86_64-linux.tar.gz | tar xz -C ~/.local/bin

# This line does all of the work: installs GHC if necessary, build the library,
# executables, and test suites, and runs the test suites. --no-terminal works
# around some quirks in Travis's terminal implementation.
script:
- mkdir -p to-travis
- stack $ARGS --no-terminal --install-ghc build --copy-bins --local-bin-path to-travis
- strip to-travis/all-cabal-metadata-tool
- bzip2 to-travis/all-cabal-metadata-tool

# Caching so the next build will be fast too.
cache:
  directories:
  - $HOME/.stack
